folders_to_parse = [
    {'url': 'ftp.zakupki.gov.ru',
     'name': 'fz223free',
     'pass': 'fz223free',
     'dir': u'/out/published/Moskva/purchaseNotice/daily',
        },
    {'url': 'ftp.zakupki.gov.ru',
     'name': 'fz223free',
     'pass': 'fz223free',
     'dir': u'/out/published/Moskva/purchaseNotice/full',
        },
    {'url': 'ftp.zakupki.gov.ru',
     'name': 'fz223free',
     'pass': 'fz223free',
     'dir': u'/out/published/Moskovskaya_obl/purchaseNotice/daily',
        },
    {'url': 'ftp.zakupki.gov.ru',
     'name': 'fz223free',
     'pass': 'fz223free',
     'dir': u'/out/published/Moskovskaya_obl/purchaseNotice/full',
        },
    {'url': 'ftp.zakupki.gov.ru',
     'name': 'fz223free',
     'pass': 'fz223free',
     'dir': u'/out/published/Sankt-Peterburg/purchaseNotice/daily',
        },
    {'url': 'ftp.zakupki.gov.ru',
     'name': 'fz223free',
     'pass': 'fz223free',
     'dir': u'/out/published/Sankt-Peterburg/purchaseNotice/full',
        },
    {'url': 'ftp.zakupki.gov.ru',
     'name': 'fz223free',
     'pass': 'fz223free',
     'dir': u'/out/published/Leningradskaya_obl/purchaseNotice/daily',
        },
    {'url': 'ftp.zakupki.gov.ru',
     'name': 'fz223free',
     'pass': 'fz223free',
     'dir': u'/out/published/Leningradskaya_obl/purchaseNotice/full',
        },
    
    ##################
     {'url': 'ftp.zakupki.gov.ru',
     'name': 'fz223free',
     'pass': 'fz223free',
     'dir': u'/out/published/Moskva/purchaseNoticeAE/daily',
        },
    {'url': 'ftp.zakupki.gov.ru',
     'name': 'fz223free',
     'pass': 'fz223free',
     'dir': u'/out/published/Moskva/purchaseNoticeAE/full',
        },
    {'url': 'ftp.zakupki.gov.ru',
     'name': 'fz223free',
     'pass': 'fz223free',
     'dir': u'/out/published/Moskovskaya_obl/purchaseNoticeAE/daily',
        },
    {'url': 'ftp.zakupki.gov.ru',
     'name': 'fz223free',
     'pass': 'fz223free',
     'dir': u'/out/published/Moskovskaya_obl/purchaseNoticeAE/full',
        },
    {'url': 'ftp.zakupki.gov.ru',
     'name': 'fz223free',
     'pass': 'fz223free',
     'dir': u'/out/published/Sankt-Peterburg/purchaseNoticeAE/daily',
        },
    {'url': 'ftp.zakupki.gov.ru',
     'name': 'fz223free',
     'pass': 'fz223free',
     'dir': u'/out/published/Sankt-Peterburg/purchaseNoticeAE/full',
        },
    {'url': 'ftp.zakupki.gov.ru',
     'name': 'fz223free',
     'pass': 'fz223free',
     'dir': u'/out/published/Leningradskaya_obl/purchaseNoticeAE/daily',
        },
    {'url': 'ftp.zakupki.gov.ru',
     'name': 'fz223free',
     'pass': 'fz223free',
     'dir': u'/out/published/Leningradskaya_obl/purchaseNoticeAE/full',
        },
                    ###########
     {'url': 'ftp.zakupki.gov.ru',
     'name': 'fz223free',
     'pass': 'fz223free',
     'dir': u'/out/published/Moskva/purchaseNoticeAE94/daily',
        },
    {'url': 'ftp.zakupki.gov.ru',
     'name': 'fz223free',
     'pass': 'fz223free',
     'dir': u'/out/published/Moskva/purchaseNoticeAE94/full',
        },
    {'url': 'ftp.zakupki.gov.ru',
     'name': 'fz223free',
     'pass': 'fz223free',
     'dir': u'/out/published/Moskovskaya_obl/purchaseNoticeAE94/daily',
        },
    {'url': 'ftp.zakupki.gov.ru',
     'name': 'fz223free',
     'pass': 'fz223free',
     'dir': u'/out/published/Moskovskaya_obl/purchaseNoticeAE94/full',
        },
    {'url': 'ftp.zakupki.gov.ru',
     'name': 'fz223free',
     'pass': 'fz223free',
     'dir': u'/out/published/Sankt-Peterburg/purchaseNoticeAE94/daily',
        },
    {'url': 'ftp.zakupki.gov.ru',
     'name': 'fz223free',
     'pass': 'fz223free',
     'dir': u'/out/published/Sankt-Peterburg/purchaseNoticeAE94/full',
        },
    {'url': 'ftp.zakupki.gov.ru',
     'name': 'fz223free',
     'pass': 'fz223free',
     'dir': u'/out/published/Leningradskaya_obl/purchaseNoticeAE94/daily',
        },
    {'url': 'ftp.zakupki.gov.ru',
     'name': 'fz223free',
     'pass': 'fz223free',
     'dir': u'/out/published/Leningradskaya_obl/purchaseNoticeAE94/full',
        },
    ##################
     {'url': 'ftp.zakupki.gov.ru',
     'name': 'fz223free',
     'pass': 'fz223free',
     'dir': u'/out/published/Moskva/purchaseNoticeEP/daily',
        },
    {'url': 'ftp.zakupki.gov.ru',
     'name': 'fz223free',
     'pass': 'fz223free',
     'dir': u'/out/published/Moskva/purchaseNoticeEP/full',
        },
    {'url': 'ftp.zakupki.gov.ru',
     'name': 'fz223free',
     'pass': 'fz223free',
     'dir': u'/out/published/Moskovskaya_obl/purchaseNoticeEP/daily',
        },
    {'url': 'ftp.zakupki.gov.ru',
     'name': 'fz223free',
     'pass': 'fz223free',
     'dir': u'/out/published/Moskovskaya_obl/purchaseNoticeEP/full',
        },
    {'url': 'ftp.zakupki.gov.ru',
     'name': 'fz223free',
     'pass': 'fz223free',
     'dir': u'/out/published/Sankt-Peterburg/purchaseNoticeEP/daily',
        },
    {'url': 'ftp.zakupki.gov.ru',
     'name': 'fz223free',
     'pass': 'fz223free',
     'dir': u'/out/published/Sankt-Peterburg/purchaseNoticeEP/full',
        },
    {'url': 'ftp.zakupki.gov.ru',
     'name': 'fz223free',
     'pass': 'fz223free',
     'dir': u'/out/published/Leningradskaya_obl/purchaseNoticeEP/daily',
        },
    {'url': 'ftp.zakupki.gov.ru',
     'name': 'fz223free',
     'pass': 'fz223free',
     'dir': u'/out/published/Leningradskaya_obl/purchaseNoticeEP/full',
        },
     ##################
     {'url': 'ftp.zakupki.gov.ru',
     'name': 'fz223free',
     'pass': 'fz223free',
     'dir': u'/out/published/Moskva/purchaseNoticeIS/daily',
        },
    {'url': 'ftp.zakupki.gov.ru',
     'name': 'fz223free',
     'pass': 'fz223free',
     'dir': u'/out/published/Moskva/purchaseNoticeIS/full',
        },
    {'url': 'ftp.zakupki.gov.ru',
     'name': 'fz223free',
     'pass': 'fz223free',
     'dir': u'/out/published/Moskovskaya_obl/purchaseNoticeIS/daily',
        },
    {'url': 'ftp.zakupki.gov.ru',
     'name': 'fz223free',
     'pass': 'fz223free',
     'dir': u'/out/published/Moskovskaya_obl/purchaseNoticeIS/full',
        },
    {'url': 'ftp.zakupki.gov.ru',
     'name': 'fz223free',
     'pass': 'fz223free',
     'dir': u'/out/published/Sankt-Peterburg/purchaseNoticeIS/daily',
        },
    {'url': 'ftp.zakupki.gov.ru',
     'name': 'fz223free',
     'pass': 'fz223free',
     'dir': u'/out/published/Sankt-Peterburg/purchaseNoticeIS/full',
        },
    {'url': 'ftp.zakupki.gov.ru',
     'name': 'fz223free',
     'pass': 'fz223free',
     'dir': u'/out/published/Leningradskaya_obl/purchaseNoticeIS/daily',
        },
    {'url': 'ftp.zakupki.gov.ru',
     'name': 'fz223free',
     'pass': 'fz223free',
     'dir': u'/out/published/Leningradskaya_obl/purchaseNoticeIS/full',
        },
     ##################
     {'url': 'ftp.zakupki.gov.ru',
     'name': 'fz223free',
     'pass': 'fz223free',
     'dir': u'/out/published/Moskva/purchaseNoticeOA/daily',
        },
    {'url': 'ftp.zakupki.gov.ru',
     'name': 'fz223free',
     'pass': 'fz223free',
     'dir': u'/out/published/Moskva/purchaseNoticeOA/full',
        },
    {'url': 'ftp.zakupki.gov.ru',
     'name': 'fz223free',
     'pass': 'fz223free',
     'dir': u'/out/published/Moskovskaya_obl/purchaseNoticeOA/daily',
        },
    {'url': 'ftp.zakupki.gov.ru',
     'name': 'fz223free',
     'pass': 'fz223free',
     'dir': u'/out/published/Moskovskaya_obl/purchaseNoticeOA/full',
        },
    {'url': 'ftp.zakupki.gov.ru',
     'name': 'fz223free',
     'pass': 'fz223free',
     'dir': u'/out/published/Sankt-Peterburg/purchaseNoticeOA/daily',
        },
    {'url': 'ftp.zakupki.gov.ru',
     'name': 'fz223free',
     'pass': 'fz223free',
     'dir': u'/out/published/Sankt-Peterburg/purchaseNoticeOA/full',
        },
    {'url': 'ftp.zakupki.gov.ru',
     'name': 'fz223free',
     'pass': 'fz223free',
     'dir': u'/out/published/Leningradskaya_obl/purchaseNoticeOA/daily',
        },
    {'url': 'ftp.zakupki.gov.ru',
     'name': 'fz223free',
     'pass': 'fz223free',
     'dir': u'/out/published/Leningradskaya_obl/purchaseNoticeOA/full',
        },
     ##################
     {'url': 'ftp.zakupki.gov.ru',
     'name': 'fz223free',
     'pass': 'fz223free',
     'dir': u'/out/published/Moskva/purchaseNoticeOK/daily',
        },
    {'url': 'ftp.zakupki.gov.ru',
     'name': 'fz223free',
     'pass': 'fz223free',
     'dir': u'/out/published/Moskva/purchaseNoticeOK/full',
        },
    {'url': 'ftp.zakupki.gov.ru',
     'name': 'fz223free',
     'pass': 'fz223free',
     'dir': u'/out/published/Moskovskaya_obl/purchaseNoticeOK/daily',
        },
    {'url': 'ftp.zakupki.gov.ru',
     'name': 'fz223free',
     'pass': 'fz223free',
     'dir': u'/out/published/Moskovskaya_obl/purchaseNoticeOK/full',
        },
    {'url': 'ftp.zakupki.gov.ru',
     'name': 'fz223free',
     'pass': 'fz223free',
     'dir': u'/out/published/Sankt-Peterburg/purchaseNoticeOK/daily',
        },
    {'url': 'ftp.zakupki.gov.ru',
     'name': 'fz223free',
     'pass': 'fz223free',
     'dir': u'/out/published/Sankt-Peterburg/purchaseNoticeOK/full',
        },
    {'url': 'ftp.zakupki.gov.ru',
     'name': 'fz223free',
     'pass': 'fz223free',
     'dir': u'/out/published/Leningradskaya_obl/purchaseNoticeOK/daily',
        },
    {'url': 'ftp.zakupki.gov.ru',
     'name': 'fz223free',
     'pass': 'fz223free',
     'dir': u'/out/published/Leningradskaya_obl/purchaseNoticeOK/full',
        },
     ##################
     {'url': 'ftp.zakupki.gov.ru',
     'name': 'fz223free',
     'pass': 'fz223free',
     'dir': u'/out/published/Moskva/purchaseNoticeZK/daily',
        },
    {'url': 'ftp.zakupki.gov.ru',
     'name': 'fz223free',
     'pass': 'fz223free',
     'dir': u'/out/published/Moskva/purchaseNoticeZK/full',
        },
    {'url': 'ftp.zakupki.gov.ru',
     'name': 'fz223free',
     'pass': 'fz223free',
     'dir': u'/out/published/Moskovskaya_obl/purchaseNoticeZK/daily',
        },
    {'url': 'ftp.zakupki.gov.ru',
     'name': 'fz223free',
     'pass': 'fz223free',
     'dir': u'/out/published/Moskovskaya_obl/purchaseNoticeZK/full',
        },
    {'url': 'ftp.zakupki.gov.ru',
     'name': 'fz223free',
     'pass': 'fz223free',
     'dir': u'/out/published/Sankt-Peterburg/purchaseNoticeZK/daily',
        },
    {'url': 'ftp.zakupki.gov.ru',
     'name': 'fz223free',
     'pass': 'fz223free',
     'dir': u'/out/published/Sankt-Peterburg/purchaseNoticeZK/full',
        },
    {'url': 'ftp.zakupki.gov.ru',
     'name': 'fz223free',
     'pass': 'fz223free',
     'dir': u'/out/published/Leningradskaya_obl/purchaseNoticeZK/daily',
        },
    {'url': 'ftp.zakupki.gov.ru',
     'name': 'fz223free',
     'pass': 'fz223free',
     'dir': u'/out/published/Leningradskaya_obl/purchaseNoticeZK/full',
        },
    {'url': 'ftp.zakupki.gov.ru',
     'name': 'free',
     'pass': 'free',
     'dir': u'/fcs_regions/Moskva/notifications/currMonth',
        },
    {'url': 'ftp.zakupki.gov.ru',
     'name': 'free',
     'pass': 'free',
     'dir': u'/fcs_regions/Moskovskaja_obl/notifications/currMonth',
        },
    {'url': 'ftp.zakupki.gov.ru',
     'name': 'free',
     'pass': 'free',
     'dir': u'/fcs_regions/Leningradskaja_obl/notifications/currMonth',
        },
    {'url': 'ftp.zakupki.gov.ru',
     'name': 'free',
     'pass': 'free',
     'dir': u'/fcs_regions/Sankt-Peterburg/notifications/currMonth',
        },
    {'url': 'ftp.zakupki.gov.ru',
     'name': 'free',
     'pass': 'free',
     'dir': u'/94fz/Moskva/notifications/daily',
        },
    {'url': 'ftp.zakupki.gov.ru',
     'name': 'free',
     'pass': 'free',
     'dir': u'/94fz/Moskovskaja_obl/notifications/daily',
        },
    {'url': 'ftp.zakupki.gov.ru',
     'name': 'free',
     'pass': 'free',
     'dir': u'/94fz/Leningradskaja_obl/notifications/daily',
        },
    {'url': 'ftp.zakupki.gov.ru',
     'name': 'free',
     'pass': 'free',
     'dir': u'/94fz/Sankt-Peterburg/notifications/daily',
        },
    ]